### ISSUE TITLE
diagnostic test as list not as string

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#148]
bullet point

eg:
* euroimmun
* luminex

**Comment by gstephan30** [comment]
in the new branch, its not visible anymore? 
![image](https://user-images.githubusercontent.com/19341690/87941312-408dd500-ca9b-11ea-8e4e-2aaeddee6a06.png)

![image](https://user-images.githubusercontent.com/19341690/87941357-526f7800-ca9b-11ea-8a55-a7ec0cfb3574.png)

but in the meta data is visible

![image](https://user-images.githubusercontent.com/19341690/87941388-61562a80-ca9b-11ea-9c90-8289a891bdbe.png)

**Comment by ulf1** [comment]
see example here

https://raw.githubusercontent.com/hzi-braunschweig/serohub/master/content/studies/muspad.de.md

**Comment by gstephan30** [comment]
![image](https://user-images.githubusercontent.com/19341690/87954136-3aecbb00-caac-11ea-95fb-ab825a7616d8.png)

![image](https://user-images.githubusercontent.com/19341690/87954172-48a24080-caac-11ea-97ba-90d9d9fd53f6.png)
