### ISSUE TITLE
alignment cooperate desing grey shades 🦘

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#21]
all boxed need gray shades. feedback of our public relations department. alignment to cooparate design.

**Comment by stephlocke** [comment]
![image](https://user-images.githubusercontent.com/6452610/86009039-95e14400-ba11-11ea-953e-517713ef0156.png)

**Comment by gstephan30** [comment]
we take the "2" ;)

**Comment by ulf1** [comment]
https://github.com/hzi-braunschweig/serohub/pull/47
