### ISSUE TITLE
date of studies wrong

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#26]
date says 1 January 0001

**Comment by stephlocke** [comment]
@gstephan30 Typically the date is the publish date of the content - that may not be veery relevant for studies. We can either remove the date from showing or you can add a `date: 2020-06-01` parameter to each md file for studies.

**Comment by ulf1** [comment]
> @gstephan30 Typically the date is the publish date of the content - that may not be veery relevant for studies. We can either remove the date from showing or you can add a `date: 2020-06-01` parameter to each md file for studies.

i'm going to comment it away
