### ISSUE TITLE
link on share data page to "next page" wrong

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#29]
it states next page: about, but the next page is the sero blog

AND date can be deleted

**Comment by stephlocke** [comment]
These links are based on pages within the same "section". In this case they are available top-level pages like about, faqs, etc. 

I can remove the pagination?

**Comment by ulf1** [comment]
> These links are based on pages within the same "section". In this case they are available top-level pages like about, faqs, etc.
> 
> I can remove the pagination?

you can comment it away.
does it also remove the pagination from the blog? (I don't mind)
