### ISSUE TITLE
Social media link appear only on "share data" and "about" page

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#30]
![image](https://user-images.githubusercontent.com/19341690/85729071-c74bce00-b6f8-11ea-9e60-fa54fd5934ec.png)

**Comment by stephlocke** [comment]
Hi Stephan, 
This is currently "as intended" the share buttons were coded to only be in the single / leaf pages. Would you like them available on all navbars?

**Comment by ulf1** [comment]
> Hi Stephan,
> This is currently "as intended" the share buttons were coded to only be in the default single page layout. Would you like them available on all navbars?

Yes

**Comment by gstephan30** [comment]
agree

**Comment by ulf1** [comment]
https://github.com/hzi-braunschweig/serohub/pull/47
