### ISSUE TITLE
DNS Forwarding does not work in the HZI Intranet

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#33]
The address https://leoss-serosurvey-plattform.helmholtz-hzi.de/ 
can be reached from the interweb but from a computer within the HZI intranet.

**Comment by stephlocke** [comment]
@ulf1 this may be because of a local dns setup inside the network. Flushing DNS caches may help.

Windows: `ipconfig /flushdns`
Linux: ` sudo /etc/init.d/networking restart`

**Comment by ulf1** [comment]
> @ulf1 this may be because of a local dns setup inside the network. Flushing DNS caches may help.
> 
> Windows: `ipconfig /flushdns`
> Linux: ` sudo /etc/init.d/networking restart`

the reason is the HZI intranet. The IT dept. is on to it
