### ISSUE TITLE
reverse baseurl change lateron

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#42]
the baseurl is set to https://serohub.netlify.app/ for the meanwhile. 
don't switch it back for the next few days!

see 
https://github.com/hzi-braunschweig/serohub/pull/41

# Status
blocked (requires the new domain https://github.com/hzi-braunschweig/serohub/issues/49)

**Comment by stephlocke** [comment]
What's the rationale on this @ulf1?
