### ISSUE TITLE
logo seruhub twitter

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#44]
change logo serohub

**Comment by stephlocke** [comment]
Did they give you a way to get just part of the logo without the text @gstephan30 ? The avatar / profile pic requirements on twitter is for it to be a square so as the logo is very rectangular you'd end up with some horrible cropping

**Comment by ulf1** [comment]
@gstephan30 
can you add the twitter login credentials to the other passwords in the intranet?

**Comment by gstephan30** [comment]
did a quick and dirty solution.
