### ISSUE TITLE
study data upload follow up

### ISSUE THREAD

**Issue by gstephan30** [hzi-braunschweig/serohub#46]
we need to discuss solutions. can you make an appointment?

**Comment by ulf1** [comment]
user story: As a researcher I need to share specific datasets with other (known) researcher

@gstephan30 Who is sharing with whom? What are possible access levels, 
a) don't share with anyone,
b) share with a certain person
c) share with all contributors
d) share to the whole world (public)

**Comment by stephlocke** [comment]
A FindATime meeting poll has been sent so we can meet at a time that works for all of us
