### ISSUE TITLE
Special information for DZIF members

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#48]
user story: As a DZIF member, I need to know about data sharing rules and regulations (e.g. expenses and allowances), so that I feel certain about participating.

where to put this information?
- extra tab (pro: DZIF member will see. Con: non DZIF member might feel excluded)
- below "share your data" 
- blog article (Con: nobody will see it)

**Comment by stephlocke** [comment]
I recommend adding to the FAQs and including a note on relevant pages linking to the FAQ 
https://github.com/hzi-braunschweig/serohub/blob/master/content/FAQ.md
