### ISSUE TITLE
rename website (again)

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#49]
the name "leoss-sero-survey" doesn't reflect the purpose of the website

TODO:
- [x] find a new name, e.g. "leoss-serosurveyhub...", "leoss-serohub...", etc.
- [ ] redesign the logo
- [ ] rename all texts 
- [ ] apply and HZI domain
- [ ] get final feedback from project stakeholder

**Comment by gstephan30** [comment]
i don't think we need a full rename. we just need to make a heading change at the first page like:

> leoss.sero-survey: seroprevalence study hub

second, I still agree, we need a more catchy url, and I would stick with _serohub_. something like serohub.org or so?

@ulf1 @Candice-Louw ?

**Comment by ulf1** [comment]
latest ideas
serohub.hzi.de
serohub.helmholtz.de

**Comment by gstephan30** [comment]
serohub.net

**Comment by gstephan30** [comment]
we probably have to consider leoss-serohub.net

**Comment by ulf1** [comment]
You can create a subdomain `leoss.serohub.net`
