### ISSUE TITLE
Logo Upload when adding a study

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#51]
TODO
- [ ] add a image upload field "logo (optional)" to the netlify CMS, https://serohub.netlify.app/admin/#/collections/studies (name it "study_logo: ..." in jekyll header)

**Comment by stephlocke** [comment]
This can be done in static/admin/config.yaml

1. add an upload location that uploaded files will be stored in 
https://www.netlifycms.org/docs/configuration-options/#media-library
2. add a field to the study collection of type image. I recommend calling this image field `image` as this is the convention for Hugo https://www.netlifycms.org/docs/widgets/#image

**Comment by ulf1** [comment]
https://github.com/hzi-braunschweig/serohub/pull/110
