### ISSUE TITLE
display all study logos at bottom of the front page

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#52]
user story: As an interested researcher, I need to see who else is participating, so that I am more certain that this website is the right place.

possible solutions
- "Contributers" section at the bottom of the front page
- seperate contributer page (Con: nobody sees it)

Related issues
- https://github.com/hzi-braunschweig/serohub/issues/51  (required)

**Comment by stephlocke** [comment]
You will need a `{{ range }}` command that operates over the studies section and presents the `.Params.Image` field using the `<img>` tag. If you wrap the img inclusion in a `{{ with }}` command you can iterate through the studies and it will only generate html img tags where the image field is present.

**Comment by ulf1** [comment]
Logo upload must be finished first
https://github.com/hzi-braunschweig/serohub/issues/51
