### ISSUE TITLE
Explanation of the term LEOSS

### ISSUE THREAD

**Issue by AlexanderHennrich** [hzi-braunschweig/serohub#59]
The Projekt seems to be linked to the DZIF LEOSS -Projekt.
But there is no link nor an explanation for that.

**Comment by ulf1** [comment]
@gstephan30 I have the same question

**Comment by ulf1** [comment]
https://leoss.net/

**Comment by gstephan30** [comment]
can I add pictures to i18n? if yes, how? @ulf1
