### ISSUE TITLE
replace generic CSS repos with internet CDNs

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#69]
see header.html

instead of 
```html
<link rel="stylesheet" href="{{ "css/font-awesome.min.css" | absURL }}">
```

use this
```html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
```
(see https://www.bootstrapcdn.com/fontawesome/)

Why?
- It will reduce the bandwidth to our website

**Comment by stephlocke** [comment]
Ulf, this improves was don improve performance for users and because of the cached nature, the netlify soft bandwidth limit of 100gb is incredibly substantial. I also set up the project in such a way that you now apply for the open-source plan which has significant increases in bandwidth too.

**Comment by ulf1** [comment]
Thank you for clarifying. I guess it's also better for offline development. We will close this issue :)
